events {}

http {
    upstream order_service {
        server order-service:8001;
    }

    server {
        listen 80;

        location /orders {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://order_service/health;
        }
    }
}
